"""
Generate daily research digest as Markdown and HTML.
"""

import logging
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import Template

from .config import TOPICS, settings
from .arxiv_fetcher import Paper
from .github_fetcher import Repo
from .rss_fetcher import BlogPost
from .hn_fetcher import HNStory

logger = logging.getLogger(__name__)


MARKDOWN_TEMPLATE = Template("""\
# 🔬 Daily Research Digest — {{ date }}

> Automatically generated by Research Monitor
> Topics: {{ topic_list }}

---

{% if papers %}
## 📄 arXiv Papers ({{ papers | length }})

{% for p in papers %}
### {{ loop.index }}. {{ p.title }}
- **Authors**: {{ p.authors | join(', ') }}
- **Published**: {{ p.published.strftime('%Y-%m-%d') }}
- **Categories**: {{ p.categories | join(', ') }}
- **Topic**: {{ p.topic_match | replace('_', ' ') | title }}
- **Keywords matched**: {{ p.relevance_keywords | join(', ') }}
- **Link**: [{{ p.url }}]({{ p.url }})
- **PDF**: [{{ p.pdf_url }}]({{ p.pdf_url }})

> {{ p.abstract }}

{% endfor %}
{% else %}
## 📄 arXiv Papers
_No new papers found today._
{% endif %}

---

{% if repos %}
## 🐙 GitHub Trending Repos ({{ repos | length }})

| # | Repo | ⭐ Stars | Language | Topic | Description |
|---|------|---------|----------|-------|-------------|
{% for r in repos %}
| {{ loop.index }} | [{{ r.full_name }}]({{ r.url }}) | {{ r.stars }} | {{ r.language }} | {{ r.topic_match | replace('_', ' ') | title }} | {{ r.description[:100] }} |
{% endfor %}

{% else %}
## 🐙 GitHub Repos
_No trending repos found today._
{% endif %}

---

{% if posts %}
## 📝 Blog Posts & Articles ({{ posts | length }})

{% for p in posts %}
### {{ loop.index }}. {{ p.title }}
- **Author**: {{ p.author }}
- **Source**: {{ p.source }}
- **Published**: {{ p.published.strftime('%Y-%m-%d') if p.published else 'N/A' }}
- **Topics**: {{ p.matched_topics | join(', ') | replace('_', ' ') | title }}
- **Keywords**: {{ p.matched_keywords | join(', ') }}
- **Link**: [{{ p.url }}]({{ p.url }})

> {{ p.summary[:200] }}...

{% endfor %}
{% else %}
## 📝 Blog Posts & Articles
_No relevant posts found today._
{% endif %}

---

{% if hn_stories %}
## 🟧 Hacker News ({{ hn_stories | length }})

| # | Title | Score | Comments | Topics |
|---|-------|-------|----------|--------|
{% for s in hn_stories %}
| {{ loop.index }} | [{{ s.title }}]({{ s.url }}) ([HN]({{ s.hn_url }})) | {{ s.score }} | {{ s.comments }} | {{ s.matched_keywords[:3] | join(', ') }} |
{% endfor %}

{% else %}
## 🟧 Hacker News
_No relevant stories today._
{% endif %}

---

## 📊 Summary

| Source | Count |
|--------|-------|
| arXiv Papers | {{ papers | length }} |
| GitHub Repos | {{ repos | length }} |
| Blog Posts | {{ posts | length }} |
| Hacker News | {{ hn_stories | length }} |
| **Total** | **{{ papers | length + repos | length + posts | length + hn_stories | length }}** |

---
_Generated at {{ now }}_
""")


HTML_TEMPLATE = Template("""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Research Digest — {{ date }}</title>
<style>
  :root {
    --bg: #0d1117; --surface: #161b22; --border: #30363d;
    --text: #e6edf3; --text-muted: #8b949e; --accent: #58a6ff;
    --green: #3fb950; --orange: #d29922; --red: #f85149;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: var(--bg); color: var(--text);
    max-width: 1000px; margin: 0 auto; padding: 2rem;
    line-height: 1.6;
  }
  h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
  h2 {
    font-size: 1.3rem; margin: 2rem 0 1rem;
    padding-bottom: 0.5rem; border-bottom: 1px solid var(--border);
  }
  h3 { font-size: 1.05rem; margin: 1rem 0 0.5rem; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  .meta { color: var(--text-muted); font-size: 0.85rem; margin: 0.3rem 0; }
  .abstract {
    background: var(--surface); border-left: 3px solid var(--accent);
    padding: 0.8rem 1rem; margin: 0.5rem 0; border-radius: 4px;
    font-size: 0.9rem; color: var(--text-muted);
  }
  .tag {
    display: inline-block; background: var(--surface); color: var(--accent);
    padding: 2px 8px; border-radius: 12px; font-size: 0.75rem;
    margin: 2px 2px;
  }
  table {
    width: 100%; border-collapse: collapse; margin: 1rem 0;
    font-size: 0.9rem;
  }
  th {
    text-align: left; padding: 0.6rem; border-bottom: 2px solid var(--border);
    color: var(--text-muted); font-weight: 600;
  }
  td { padding: 0.6rem; border-bottom: 1px solid var(--border); }
  tr:hover td { background: var(--surface); }
  .summary-grid {
    display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 1rem; margin: 1rem 0;
  }
  .summary-card {
    background: var(--surface); border: 1px solid var(--border);
    border-radius: 8px; padding: 1.2rem; text-align: center;
  }
  .summary-card .number {
    font-size: 2rem; font-weight: bold; color: var(--accent);
  }
  .summary-card .label { color: var(--text-muted); font-size: 0.85rem; }
  .section { margin-bottom: 2rem; }
  .paper, .post { margin-bottom: 1.5rem; }
  footer { margin-top: 3rem; color: var(--text-muted); font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>

<h1>🔬 Daily Research Digest</h1>
<p class="meta">{{ date }} · Topics: {{ topic_list }}</p>

<div class="summary-grid">
  <div class="summary-card"><div class="number">{{ papers | length }}</div><div class="label">arXiv Papers</div></div>
  <div class="summary-card"><div class="number">{{ repos | length }}</div><div class="label">GitHub Repos</div></div>
  <div class="summary-card"><div class="number">{{ posts | length }}</div><div class="label">Blog Posts</div></div>
  <div class="summary-card"><div class="number">{{ hn_stories | length }}</div><div class="label">HN Stories</div></div>
</div>

{% if papers %}
<div class="section">
<h2>📄 arXiv Papers</h2>
{% for p in papers %}
<div class="paper">
  <h3><a href="{{ p.url }}">{{ p.title }}</a></h3>
  <p class="meta">{{ p.authors | join(', ') }} · {{ p.published.strftime('%Y-%m-%d') }}</p>
  <p class="meta">{{ p.categories | join(', ') }}</p>
  <div>{% for kw in p.relevance_keywords %}<span class="tag">{{ kw }}</span>{% endfor %}</div>
  <div class="abstract">{{ p.abstract }}</div>
  <p class="meta"><a href="{{ p.pdf_url }}">📥 PDF</a></p>
</div>
{% endfor %}
</div>
{% endif %}

{% if repos %}
<div class="section">
<h2>🐙 GitHub Repos</h2>
<table>
  <thead><tr><th>#</th><th>Repo</th><th>⭐</th><th>Lang</th><th>Topic</th><th>Description</th></tr></thead>
  <tbody>
  {% for r in repos %}
  <tr>
    <td>{{ loop.index }}</td>
    <td><a href="{{ r.url }}">{{ r.full_name }}</a></td>
    <td>{{ r.stars }}</td>
    <td>{{ r.language }}</td>
    <td><span class="tag">{{ r.topic_match | replace('_', ' ') }}</span></td>
    <td>{{ r.description[:120] }}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
</div>
{% endif %}

{% if posts %}
<div class="section">
<h2>📝 Blog Posts & Articles</h2>
{% for p in posts %}
<div class="post">
  <h3><a href="{{ p.url }}">{{ p.title }}</a></h3>
  <p class="meta">{{ p.author }} · {{ p.source }} · {{ p.published.strftime('%Y-%m-%d') if p.published else 'N/A' }}</p>
  <div>{% for kw in p.matched_keywords %}<span class="tag">{{ kw }}</span>{% endfor %}</div>
  <div class="abstract">{{ p.summary[:250] }}</div>
</div>
{% endfor %}
</div>
{% endif %}

{% if hn_stories %}
<div class="section">
<h2>🟧 Hacker News</h2>
<table>
  <thead><tr><th>#</th><th>Title</th><th>Score</th><th>Comments</th><th>Topics</th></tr></thead>
  <tbody>
  {% for s in hn_stories %}
  <tr>
    <td>{{ loop.index }}</td>
    <td><a href="{{ s.url }}">{{ s.title }}</a> <a href="{{ s.hn_url }}" class="meta">[HN]</a></td>
    <td>{{ s.score }}</td>
    <td>{{ s.comments }}</td>
    <td>{% for kw in s.matched_keywords[:3] %}<span class="tag">{{ kw }}</span>{% endfor %}</td>
  </tr>
  {% endfor %}
  </tbody>
</table>
</div>
{% endif %}

<footer>Generated at {{ now }} by Research Monitor</footer>
</body>
</html>
""")


def generate_report(
    papers: list[Paper],
    repos: list[Repo],
    posts: list[BlogPost],
    hn_stories: list[HNStory],
) -> tuple[Path, Path]:
    """Generate both Markdown and HTML reports, return their paths."""

    now = datetime.now(timezone.utc)
    date_str = now.strftime("%Y-%m-%d")
    now_str = now.strftime("%Y-%m-%d %H:%M UTC")
    topic_list = ", ".join(
        cfg["description"] for cfg in TOPICS.values()
    )

    reports_dir = Path(settings.reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)

    ctx = {
        "date": date_str,
        "now": now_str,
        "topic_list": topic_list,
        "papers": papers,
        "repos": repos,
        "posts": posts,
        "hn_stories": hn_stories,
    }

    md_path = reports_dir / f"digest-{date_str}.md"
    md_content = MARKDOWN_TEMPLATE.render(**ctx)
    md_path.write_text(md_content, encoding="utf-8")
    logger.info("Markdown report saved to %s", md_path)

    html_path = reports_dir / f"digest-{date_str}.html"
    html_content = HTML_TEMPLATE.render(**ctx)
    html_path.write_text(html_content, encoding="utf-8")
    logger.info("HTML report saved to %s", html_path)

    return md_path, html_path
